version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'chalk'
        versions: ['5.x']
      - dependency-name: 'node-fetch'
        versions: ['2.6.x']
      - dependency-name: 'storybook'
      - dependency-name: '@storybook/*'
