description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 9
    - uses: actions/setup-node@v3
      with:
        cache: pnpm
        node-version: '22'
    - run: |
        pnpm install --no-frozen-lockfile
        pnpm prisma generate
      shell: bash
  using: composite
