name: Build
on:
  pull_request: ~
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - name: Setup .env
        run: mv .env.sample .env
      - name: Build
        run: pnpm build
