name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: mv .env.visitor .env
      - run: yarn install
      - run: yarn typecheck
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: mv .env.visitor .env
      - run: yarn install
      - run: yarn build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: mv .env.visitor .env
      - run: yarn install
      - run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: mv .env.visitor .env
      - run: yarn install
      - run: yarn lint
  cypress-e2e-visitor-side:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: mv .env.visitor .env
      - run: docker-compose up -d
      - uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/visitor_basic.js
          start: yarn server:start, yarn start
          wait-on: 'http://localhost:3000'
  cypress-e2e-admin-side:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: mv .env.admin .env
      - run: docker-compose up -d
      - uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/admin_basic.js
          start: yarn server:start, yarn start
          wait-on: 'http://localhost:3000'
