name: Cypress E2E Admin Side
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  cypress-e2e-admin-side:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: mv .env.admin .env
      - run: docker-compose up -d
      - uses: cypress-io/github-action@v2
        with:
          spec: cypress/integration/admin_basic.js,cypress/integration/admin_basic_mobile.js
          start: yarn server:start, yarn start
          wait-on: 'http://localhost:3000'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
