name: Playwright Admin Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Create .env file
        run: cp .env.e2e .env
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: install Playwright browsers
        run: pnpm exec playwright install
      - name: Build Frontend App
        run: pnpm build:e2e
      - name: docker compose run
        run: docker compose up -d
      - name: Apply DB schema
        run: pnpm prisma migrate dev
      - name: Run Playwright tests
        run: pnpm exec playwright test admin.spec.ts
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
