name: Typecheck
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/prepare
      - uses: actions/checkout@v3
      - name: Typecheck
        run: pnpm typecheck
