name: Typecheck
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '16.8'
      - run: mv .env.visitor .env
      - run: yarn install
      - run: yarn typecheck:all
